version: 0.0
os: linux

files:
  - source: /
    destination: home/ubuntu/mapgoblin

permissions:
  - object: home/ubuntu/mapgoblin
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root